import black
import logging
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
RESOURCES_PATH = REPO_ROOT / "resources"
CODE_PATH = REPO_ROOT / "rigour" / "data"

logging.basicConfig(level=logging.INFO)


def write_python(file_path: Path, content: str) -> None:
    mode = black.Mode()
    formatted_code = black.format_str(content, mode=mode)

    # Write the formatted code to a file
    with open(file_path, "w", encoding="utf-8") as fh:
        fh.write("# This file is automatically generated, do not edit it.\n")
        fh.write(formatted_code)
