import logging
import subprocess
import unicodedata
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import orjson
from normality.cleaning import remove_unsafe_chars
from ruff import find_ruff_bin

REPO_ROOT = Path(__file__).parent.parent
RESOURCES_PATH = REPO_ROOT / "resources"
CODE_PATH = REPO_ROOT / "rigour" / "data"
RUST_DATA_PATH = REPO_ROOT / "rust" / "data"
RUST_GENERATED_PATH = REPO_ROOT / "rust" / "src" / "generated"

logging.basicConfig(level=logging.INFO)


def norm_string(data: Any) -> str:
    """Normalize a string to avoid duplication and provide standardized forms."""
    text = str(data)
    text = unicodedata.normalize("NFC", text)
    text = remove_unsafe_chars(text)
    return text.strip()


def write_python(file_path: Path, content: str) -> None:
    """Format generated Python source and write it to disk.

    Formatting has to shell out: the `ruff` distribution is a Rust binary plus a
    locator shim, and exposes no formatting API. `find_ruff_bin()` resolves the
    binary that ships with the installed package, so output does not depend on
    what happens to be on PATH.
    """
    proc = subprocess.run(
        [find_ruff_bin(), "format", "-"],
        input=content,
        capture_output=True,
        text=True,
        check=False,  # handled below, so ruff's stderr makes it into the message
    )
    if proc.returncode != 0:
        raise RuntimeError(f"ruff format failed for {file_path}: {proc.stderr.strip()}")

    with open(file_path, "w", encoding="utf-8") as fh:
        fh.write("# This file is automatically generated, do not edit it.\n")
        fh.write(proc.stdout)


def write_jsonl(file_path: Path, data: Iterable[Any]) -> None:
    """Write a list of dictionaries to a JSONL file."""
    with open(file_path, "wb") as fh:
        fh.writelines(orjson.dumps(item, option=orjson.OPT_APPEND_NEWLINE) for item in data)


def write_json(file_path: Path, data: Any, indent: bool = False) -> None:
    """Write a single JSON document to disk.

    Used for Tier-3 Rust data artifacts (structured records that the Rust
    crate deserialises via serde inside a LazyLock). Output is sorted and
    2-space-indented so the file diffs cleanly in PRs when YAML sources
    change.
    """
    opts = orjson.OPT_SORT_KEYS | orjson.OPT_APPEND_NEWLINE
    if indent:
        opts |= orjson.OPT_INDENT_2
    with open(file_path, "wb") as fh:
        fh.write(orjson.dumps(data, option=opts))
