site_name: rigour
repo_url: https://github.com/opensanctions/rigour

theme:
  name: material
  logo: https://assets.opensanctions.org/images/ura/logo_white.png
  favicon: https://assets.opensanctions.org/images/favicon-32x32.png
  palette:
    primary: custom
    accent: custom
  custom_dir: docs/overrides
  features:
    - navigation.sections
extra_css: [stylesheets/extra.css]

extra:
  social:
    - icon: material/forum
      link: https://discuss.opensanctions.org/
    - icon: material/github
      link: https://github.com/opensanctions/rigour
    - icon: material/linkedin
      link: https://www.linkedin.com/company/opensanctions/
    - icon: material/web
      link: https://www.opensanctions.org

plugins:
  - search
  - autorefs
  # - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Overview: index.md
  - Data assets: data.md
  - Data types:
      - Names: names.md
      - Identifiers: ids.md
      - Territories: territories.md
      - Addresses: addresses.md
      - Languages: langs.md
      - MIME types: mime.md
      - URLs: urls.md
      - Text: text.md
      - Other: misc.md

  - Toolchain:
      - followthemoney: https://followthemoney.tech/
      # - rigour: https://rigour.followthemoney.tech/
      - yente: https://yente.followthemoney.tech/
      - OpenAleph: https://openaleph.org/docs/
      - OpenSanctions: https://www.opensanctions.org/docs/
