import black
from pathlib import Path


def write_python(file_path: Path, content: str) -> None:
    mode = black.Mode()
    formatted_code = black.format_str(content, mode=mode)

    # Write the formatted code to a file
    with open(file_path, "w", encoding="utf-8") as fh:
        fh.write("# This file is automatically generated, do not edit it.\n")
        fh.write(formatted_code)
