import os
import yaml
import logging

from rigour.data import DATA_PATH

log = logging.getLogger(__name__)

TEMPLATE = """# This file is automatically generated, do not edit it.
from typing import Dict, Any

WORLD: Dict[str, Any] = %r
"""


def update_data() -> None:
    lang_path = DATA_PATH / "countries"
    path = os.path.dirname(__file__)
    source_file = os.path.join(path, lang_path / "world.yml")
    with open(source_file, "r", encoding="utf-8") as ufh:
        world = yaml.safe_load(ufh.read())

    for code, data in world.items():
        data['country'] = data.get('country', False)
        assert isinstance(data['country'], bool)

    with open(lang_path / "world.py", "w", encoding="utf-8") as ofh:
        data = TEMPLATE % world
        ofh.write(data)


if __name__ == "__main__":
    update_data()
