def metaphone(token: str) -> str: ...
def soundex(token: str) -> str: ...
def codepoint_script(cp: int) -> str | None: ...
def text_scripts(text: str) -> set[str]: ...
def latinize_text(text: str) -> str: ...
def ascii_text(text: str) -> str: ...
def _normalize(text: str, flags: int, cleanup: int) -> str | None: ...
def _ffi_noop(text: str) -> str: ...
def replace_org_types_compare(text: str, flags: int, cleanup: int, generic: bool) -> str: ...
def replace_org_types_display(text: str, flags: int, cleanup: int) -> str: ...
def remove_org_types(text: str, flags: int, cleanup: int, replacement: str) -> str: ...
def extract_org_types(
    text: str, flags: int, cleanup: int, generic: bool
) -> list[tuple[str, str]]: ...
